@timestamp = {{$timestamp}}

### 打开 SSE 连接（Hapi，端口 3030）
GET http://localhost:3030/sse?userId=alice
Accept: text/event-stream

### 向 alice 发送定向通知
POST http://localhost:3030/notify/alice
Content-Type: application/json

{
  "msg": "hi alice (hapi)",
  "time": "{{timestamp}}"
}

### 全员广播
POST http://localhost:3030/broadcast
Content-Type: application/json

{
  "msg": "broadcast from hapi",
  "time": "{{timestamp}}"
}

### 向房间 global 发送
POST http://localhost:3030/room/global
Content-Type: application/json

{
  "msg": "room message (hapi)",
  "time": "{{timestamp}}"
}

### 发布到房间 global（若已实现并配置 Redis）
POST http://localhost:3030/publish-room/global
Content-Type: application/json

{
  "msg": "published room message (hapi)",
  "time": "{{timestamp}}"
}
